export const projectJSON = [
    {id:'1', name: 'Hydrogen', status: 'online'},
    {id:'2', name: 'Helium', status: 'offline'},
    {id:'3', name: 'Lithium', status: 'admin'},
    {id:'4', name: 'Beryllium', status: 'not aviable'},
    {id:'5', name: 'Boron', status: 'targeted'},
    {id:'6', name: 'Carbon', status: 'online'},
    {id:'7', name: 'Nitrogen', status: 'online'},
    {id:'8', name: 'Oxygen', status: 'online'},
    {id:'9', name: 'Fluorine', status: 'online'},
    {id:'10', name: 'Neon', status: 'online'},
    {id:'11', name: 'Sodium', status: 'online'},
    {id:'12', name: 'Magnesium', status: 'online'},
    {id:'13', name: 'Aluminum', status: 'online'},
    {id:'14', name: 'Silicon', status: 'online'},
    {id:'15', name: 'Phosphorus', status: 'online'},
    {id:'16', name: 'Sulfur', status: 'online'},
    {id:'17', name: 'Chlorine', status: 'online'},
    {id:'18', name: 'Argon', status: 'online'},
    {id:'19', name: 'Potassium', status: 'online'},
    {id:'20', name: 'Calcium', status: 'online'},
];